### ISSUE TITLE
Frage: Werden Züge bei beschädigung eingefroren?

### ISSUE THREAD

**Issue by asw631** [Loisel/piraterace#17]
sollten wir auch einführen. ich glaube 10 Schadenspunkte wären gut. alle 2 Treffer wird eine Karte fest. man wird quasi manövrierunfähig.

zum Reparieren muss man am Hafen anlanden. oder man hat in ner Schatzkiste Werkzeug gefunden....

**Comment by jakubfabian** [comment]
also ausgeführt werden die karten schon aber man kann sie nicht mehr vertauschen. ist bereits eingebaut. Fahr mal gegen steine.
